spring.application.name=Vehicle Service Management System

spring.datasource.url=jdbc:postgresql://postgres:5432/vehicleservicedb
spring.datasource.username=danish
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ai.service.url=${AI_SERVICE_URL:http://localhost:8000}